export const FETCH_POPULAR_FILMS = "FETCH_POPULAR_FILMS";
export const FETCH_GENRES = "FETCH_GENRES";
export const ADD_POPULAR_FILMS = "ADD_POPULAR_FILMS";
export const ADD_SCROLL_LOADED_FILMS = "ADD_SCROLL_LOADED_FILMS";
export const ADD_IN_FAVORITES = "ADD_IN_FAVORITES";
export const LOAD_FAVORITES = "LOAD_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const ADD_GENRES = "ADD_GENRES";

